# .github/workflows/main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  trigger-build-workflow:
    uses: ./.github/workflows/build.yml
