# .github/workflows/build.yml
name: Build Dockerfile

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: |
          echo "FROM alpine"
