# .github/workflows/build.yml
name: Build Dockerfile

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: false
          tags: ${{ github.repository }}:latest
          build-args: |
            AUTH_TOKEN="HELLO_TOKEN"
